<?php

namespace FormerStudentsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormerStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormerStudentRepository extends EntityRepository
{
}
